/** ExplorerImageIndex from Studio's ReflectionMetadata.xml. Unlisted classes use 0, Studio's default. */
export const CLASS_IMAGE_INDEX: Record<string, number> = {
  Accessory: 32,
  AccessoryDescription: 104,
  Accoutrement: 32,
  AlignOrientation: 100,
  AlignPosition: 99,
  AngularVelocity: 103,
  AnimationConstraint: 0,
  Attachment: 81,
  BallSocketConstraint: 86,
  BasePart: 0,
  BaseScript: 0,
  BaseWrap: 0,
  BoolValue: 4,
  Constraint: 86,
  CylindricalConstraint: 95,
  DataModel: 0,
  Folder: 77,
  Hat: 45,
  HingeConstraint: 87,
  Instance: 0,
  IntersectOperation: 0,
  Lighting: 13,
  LineForce: 101,
  LinearVelocity: 132,
  LuaSourceContainer: 0,
  MaterialService: 131,
  MaterialVariant: 130,
  MeshPart: 73,
  Model: 2,
  ModuleScript: 76,
  NegateOperation: 72,
  NoCollisionConstraint: 105,
  NumberValue: 4,
  ObjectValue: 4,
  PVInstance: 0,
  Part: 1,
  PartOperation: 0,
  Plane: 134,
  PlaneConstraint: 134,
  PrismaticConstraint: 88,
  ReplicatedStorage: 70,
  RigidConstraint: 135,
  RodConstraint: 90,
  RopeConstraint: 89,
  Script: 6,
  ServerScriptService: 71,
  SlidingBallConstraint: 88,
  SpringConstraint: 91,
  StringValue: 4,
  SurfaceAppearance: 10,
  Terrain: 65,
  TerrainDetail: 144,
  Torque: 103,
  TorsionSpringConstraint: 125,
  TriangleMeshPart: 0,
  UIAspectRatioConstraint: 26,
  UIComponent: 0,
  UIConstraint: 0,
  UISizeConstraint: 26,
  UITextSizeConstraint: 26,
  UnionOperation: 73,
  UniversalConstraint: 123,
  ValueBase: 4,
  VectorForce: 102,
  WeldConstraint: 94,
  Workspace: 19,
  WrapDeformer: 127,
  WrapLayer: 126,
  WrapTarget: 127,
  WrapTextureTransfer: 0,
}

export const CLASS_IMAGE_COUNT = 147

export function classImageIndex(className: string): number {
  return CLASS_IMAGE_INDEX[className] ?? 0
}
