import type { ClassSchema, PropertySchema, Variant } from './types'

const str = (value = ''): Variant => ({ type: 'string', value })
const bool = (value = false): Variant => ({ type: 'bool', value })
const num = (value = 0): Variant => ({ type: 'number', value })
const enm = (value: string): Variant => ({ type: 'enum', value })
const v2 = (x = 0, y = 0): Variant => ({ type: 'Vector2', value: { x, y } })
const v3 = (x = 0, y = 0, z = 0): Variant => ({ type: 'Vector3', value: { x, y, z } })
const color = (r = 1, g = 1, b = 1): Variant => ({ type: 'Color3', value: { r, g, b } })
const cf = (x = 0, y = 0, z = 0): Variant => ({
  type: 'CFrame',
  value: { position: { x, y, z }, orientation: { x: 0, y: 0, z: 0 } },
})
const ref = (): Variant => ({ type: 'Instance', value: null })

const prop = (
  name: string,
  category: string,
  defaultValue: Variant,
  extra: Partial<PropertySchema> = {},
): PropertySchema => ({ name, category, type: defaultValue.type, defaultValue, ...extra })
const enumProp = (name: string, category: string, values: string[], initial = values[0]): PropertySchema =>
  prop(name, category, enm(initial), { enumValues: values })
const refProp = (name: string, category = 'Data', referenceClass?: string, readOnly = false): PropertySchema =>
  prop(name, category, ref(), { referenceClass, readOnly })

const ACCESSORY_TYPES = [
  'Unknown',
  'Hat',
  'Hair',
  'Face',
  'Neck',
  'Shoulder',
  'Front',
  'Back',
  'Waist',
  'TShirt',
  'Shirt',
  'Pants',
  'Jacket',
  'Sweater',
  'Shorts',
  'LeftShoe',
  'RightShoe',
  'DressSkirt',
  'Eyebrow',
  'Eyelash',
]
const MATERIALS = [
  'Plastic',
  'SmoothPlastic',
  'Wood',
  'WoodPlanks',
  'Metal',
  'Concrete',
  'Brick',
  'Grass',
  'Glass',
  'Neon',
  'Fabric',
  'Rock',
  'Sand',
]
const COLLISION_FIDELITY = ['Default', 'Hull', 'Box', 'PreciseConvexDecomposition', 'Tunable']
const FLUID_FIDELITY = ['Automatic', 'UseCollisionGeometry', 'UsePreciseGeometry']
const RENDER_FIDELITY = ['Automatic', 'Precise', 'Performance']
const AXES = ['World', 'Attachment0', 'Attachment1']
const ACTUATORS = ['None', 'Motor', 'Servo']

const textureProps = (): PropertySchema[] => [
  prop('ColorMap', 'Appearance', str()),
  prop('MetalnessMap', 'Appearance', str()),
  prop('NormalMap', 'Appearance', str()),
  prop('RoughnessMap', 'Appearance', str()),
  prop('EmissiveMaskContent', 'Appearance', str()),
  prop('EmissiveStrength', 'Appearance', num(1), { min: 0 }),
  prop('EmissiveTint', 'Appearance', color()),
]

const constraintBase = (): PropertySchema[] => [
  refProp('Attachment0', 'Data', 'Attachment'),
  refProp('Attachment1', 'Data', 'Attachment'),
  prop('Enabled', 'Behavior', bool(true)),
  prop('Active', 'Behavior', bool(false), { readOnly: true }),
  prop('Color', 'Appearance', color(1, 0.67, 0)),
  prop('Visible', 'Appearance', bool(false)),
]

const springLike = (): PropertySchema[] => [
  prop('Coils', 'Appearance', num(8), { min: 0 }),
  prop('Damping', 'Behavior', num(0), { min: 0 }),
  prop('LimitsEnabled', 'Behavior', bool(false)),
  prop('Radius', 'Appearance', num(0.5), { min: 0 }),
  prop('Stiffness', 'Behavior', num(0), { min: 0 }),
  prop('Thickness', 'Appearance', num(0.1), { min: 0 }),
]

export const EXTENDED_CLASS_LIST: ClassSchema[] = [
  {
    className: 'TriangleMeshPart',
    superClass: 'BasePart',
    creatable: false,
    description: 'Abstract mesh geometry shared by MeshPart and CSG part operations.',
    glyph: 'TM',
    glyphColor: '#8a8a8a',
    properties: [
      prop('MeshSize', 'Part', v3(4, 1, 2), { readOnly: true }),
      enumProp('CollisionFidelity', 'Collision', COLLISION_FIDELITY),
      prop('CollisionPrecision', 'Collision', num(0), { min: 0, max: 1, step: 0.05 }),
      enumProp('FluidFidelity', 'Behavior', FLUID_FIDELITY),
    ],
  },
  {
    className: 'MeshPart',
    superClass: 'TriangleMeshPart',
    creatable: true,
    description: 'A BasePart whose visible geometry comes from a mesh asset.',
    glyph: 'MP',
    glyphColor: '#4da3d9',
    properties: [
      prop('MeshId', 'Appearance', str('rbxassetid://')),
      prop('TextureID', 'Appearance', str()),
      prop('DoubleSided', 'Appearance', bool(false)),
      prop('HasSkinnedMesh', 'Data', bool(false), { readOnly: true }),
      enumProp('RenderFidelity', 'Appearance', RENDER_FIDELITY),
      prop('VertexCount', 'Data', num(0), { readOnly: true }),
      prop('InitialSize', 'Data', v3(4, 1, 2), { readOnly: true }),
    ],
  },
  {
    className: 'SurfaceAppearance',
    superClass: 'Instance',
    creatable: true,
    description: 'PBR texture maps applied to a MeshPart.',
    glyph: 'SA',
    glyphColor: '#d99754',
    properties: [
      prop('Color', 'Appearance', color()),
      ...textureProps(),
      enumProp('AlphaMode', 'Appearance', ['Overlay', 'Transparency', 'TintMask', 'Opaque'], 'Overlay'),
      enumProp('ResampleMode', 'Appearance', ['Default', 'Pixelated']),
      prop('TexturePack', 'Appearance', str()),
    ],
  },
  {
    className: 'MaterialService',
    superClass: 'Instance',
    creatable: false,
    isService: true,
    description: 'Service that owns MaterialVariant instances and material overrides.',
    glyph: 'MS',
    glyphColor: '#c984d6',
    properties: [prop('Use2022Materials', 'Material Pack', bool(true))],
  },
  {
    className: 'MaterialVariant',
    superClass: 'Instance',
    creatable: true,
    fixedParentClass: 'MaterialService',
    description: 'Custom material maps and physical behavior for a base material.',
    glyph: 'MV',
    glyphColor: '#b985d1',
    properties: [
      ...textureProps(),
      enumProp('BaseMaterial', 'Appearance', MATERIALS),
      enumProp('MaterialPattern', 'Appearance', ['Regular', 'Organic']),
      prop('StudsPerTile', 'Appearance', num(10), { min: 0.1 }),
      enumProp('AlphaMode', 'Appearance', ['Opaque', 'Overlay', 'Transparency', 'TintMask'], 'Opaque'),
    ],
  },
  {
    className: 'Accoutrement',
    superClass: 'Instance',
    creatable: false,
    description: 'Abstract base for wearable avatar accessories.',
    glyph: 'AC',
    glyphColor: '#8a8a8a',
    properties: [prop('AttachmentPoint', 'Transform', cf())],
  },
  {
    className: 'Accessory',
    superClass: 'Accoutrement',
    creatable: true,
    description: 'Rigid or layered cosmetic item attached to a character.',
    glyph: 'A',
    glyphColor: '#e6a45e',
    properties: [enumProp('AccessoryType', 'Data', ACCESSORY_TYPES)],
  },
  {
    className: 'Hat',
    superClass: 'Accoutrement',
    creatable: true,
    description: 'Legacy hat accessory.',
    glyph: 'H',
    glyphColor: '#d89756',
    properties: [],
  },
  {
    className: 'AccessoryDescription',
    superClass: 'Instance',
    creatable: true,
    description: 'Describes an accessory asset and its avatar adjustment.',
    glyph: 'AD',
    glyphColor: '#e0a874',
    properties: [
      prop('AssetId', 'Data', num(0)),
      refProp('Instance', 'Data', 'Instance'),
      prop('Order', 'Data', num(0)),
      prop('IsLayered', 'Data', bool(false)),
      prop('Position', 'Transform', v3()),
      prop('Rotation', 'Transform', v3()),
      prop('Scale', 'Transform', v3(1, 1, 1)),
      enumProp('AccessoryType', 'Data', ACCESSORY_TYPES),
    ],
  },
  {
    className: 'BaseWrap',
    superClass: 'Instance',
    creatable: false,
    description: 'Abstract cage mesh data used by layered deformation.',
    glyph: 'BW',
    glyphColor: '#8a8a8a',
    properties: [
      prop('CageMeshId', 'Appearance', str()),
      prop('CageOrigin', 'Transform', cf()),
      prop('ImportOrigin', 'Transform', cf()),
      prop('CageOriginWorld', 'Derived World Data', cf(), { readOnly: true }),
      prop('ImportOriginWorld', 'Derived World Data', cf(), { readOnly: true }),
    ],
  },
  {
    className: 'WrapLayer',
    superClass: 'BaseWrap',
    creatable: true,
    description: 'Layered clothing cage that deforms around a WrapTarget.',
    glyph: 'WL',
    glyphColor: '#6bb6a8',
    properties: [
      prop('BindOffset', 'Transform', cf()),
      prop('Enabled', 'Behavior', bool(true)),
      prop('Order', 'Tuning', num(1)),
      prop('ReferenceMeshId', 'Appearance', str()),
      prop('ReferenceOrigin', 'Transform', cf()),
      prop('ReferenceOriginWorld', 'Derived World Data', cf(), { readOnly: true }),
      enumProp('AutoSkin', 'Behavior', ['Disabled', 'EnabledPreserve', 'EnabledOverride']),
      prop('Color', 'Appearance', color()),
      prop('MaxSize', 'Tuning', v3()),
      prop('Offset', 'Tuning', v3()),
    ],
  },
  {
    className: 'WrapTarget',
    superClass: 'BaseWrap',
    creatable: true,
    description: 'Body cage that receives layered accessory deformation.',
    glyph: 'WT',
    glyphColor: '#70b7bd',
    properties: [prop('Color', 'Appearance', color())],
  },
  {
    className: 'WrapDeformer',
    superClass: 'BaseWrap',
    creatable: true,
    description: 'Generic cage-based mesh deformer.',
    glyph: 'WD',
    glyphColor: '#69a9b4',
    properties: [],
  },
  {
    className: 'WrapTextureTransfer',
    superClass: 'Instance',
    creatable: true,
    description: 'Transfers UV texture data through a compatible cage.',
    glyph: 'TX',
    glyphColor: '#6f9fc4',
    properties: [
      prop('ReferenceCageMeshContent', 'Appearance', str()),
      prop('UVMinBound', 'Appearance', v2()),
      prop('UVMaxBound', 'Appearance', v2(1, 1)),
    ],
  },
  {
    className: 'Attachment',
    superClass: 'Instance',
    creatable: true,
    description: 'A coordinate frame used to connect constraints and accessories.',
    glyph: 'AT',
    glyphColor: '#f0c85b',
    properties: [
      prop('CFrame', 'Transform', cf()),
      prop('Visible', 'Appearance', bool(false)),
      prop('Axis', 'Derived Data', v3(1, 0, 0)),
      prop('SecondaryAxis', 'Derived Data', v3(0, 1, 0)),
      prop('WorldCFrame', 'Derived World Data', cf(), { readOnly: true }),
      prop('WorldPosition', 'Derived World Data', v3(), { readOnly: true }),
      prop('WorldAxis', 'Derived World Data', v3(1, 0, 0), { readOnly: true }),
      prop('WorldSecondaryAxis', 'Derived World Data', v3(0, 1, 0), { readOnly: true }),
    ],
  },
  {
    className: 'Terrain',
    superClass: 'BasePart',
    creatable: false,
    protected: true,
    fixedParentClass: 'Workspace',
    singletonPerParent: true,
    description: 'Locked smooth-voxel terrain. Every Workspace owns at most one.',
    glyph: 'T',
    glyphColor: '#66a05d',
    properties: [
      prop('Name', 'Data', str('Terrain'), { storage: 'name', readOnly: true }),
      prop('Decoration', 'Appearance', bool(false)),
      prop('GrassLength', 'Appearance', num(0.7), { min: 0.1, max: 1, step: 0.05 }),
      prop('WaterColor', 'Appearance', color(0.05, 0.33, 0.36)),
      prop('WaterReflectance', 'Appearance', num(1), { min: 0, max: 1, step: 0.05 }),
      prop('WaterTransparency', 'Appearance', num(0.3), { min: 0, max: 1, step: 0.05 }),
      prop('WaterWaveSize', 'Appearance', num(0.15), { min: 0, max: 1, step: 0.05 }),
      prop('WaterWaveSpeed', 'Appearance', num(10), { min: 0, max: 100 }),
      prop('MaxExtents', 'Data', str('Region3int16(-32000..32000 cells)'), { readOnly: true }),
      ...['Color', 'Material', 'Transparency', 'Reflectance', 'CastShadow', 'Size', 'CFrame', 'Anchored', 'Locked'].map(
        (name) => prop(name, 'Internal', str(), { hidden: true }),
      ),
    ],
  },
  {
    className: 'TerrainDetail',
    superClass: 'Instance',
    creatable: true,
    fixedParentClass: 'MaterialVariant',
    description: 'Per-face terrain material textures owned by a MaterialVariant.',
    glyph: 'TD',
    glyphColor: '#7da96a',
    properties: [
      enumProp('Face', 'Appearance', ['Top', 'Side', 'Bottom'], 'Side'),
      enumProp('MaterialPattern', 'Appearance', ['Regular', 'Organic']),
      ...textureProps(),
      prop('StudsPerTile', 'Appearance', num(10), { min: 0.1 }),
    ],
  },
  {
    className: 'Constraint',
    superClass: 'Instance',
    creatable: false,
    description: 'Abstract base for physics constraints connected by Attachments.',
    glyph: 'C',
    glyphColor: '#8a8a8a',
    properties: constraintBase(),
  },
  {
    className: 'PlaneConstraint',
    superClass: 'Constraint',
    creatable: true,
    description: 'Constrains motion to a plane.',
    glyph: 'PC',
    glyphColor: '#dd9650',
    properties: [],
  },
  {
    className: 'Plane',
    superClass: 'PlaneConstraint',
    creatable: true,
    description: 'Deprecated plane constraint alias.',
    glyph: 'PL',
    glyphColor: '#c98d55',
    properties: [],
  },
  {
    className: 'RigidConstraint',
    superClass: 'Constraint',
    creatable: true,
    description: 'Rigidly connects two Attachments.',
    glyph: 'RC',
    glyphColor: '#e39b4b',
    properties: [],
  },
  {
    className: 'BallSocketConstraint',
    superClass: 'Constraint',
    creatable: true,
    description: 'Allows free rotation with optional angular and twist limits.',
    glyph: 'BS',
    glyphColor: '#dd9348',
    properties: [
      prop('LimitsEnabled', 'Limits', bool(false)),
      prop('MaxFrictionTorque', 'Friction', num(0), { min: 0 }),
      prop('Radius', 'Appearance', num(0.15), { min: 0 }),
      prop('Restitution', 'Limits', num(0), { min: 0, max: 1 }),
      prop('TwistLimitsEnabled', 'Twist Limits', bool(false)),
      prop('TwistLowerAngle', 'Twist Limits', num(-45)),
      prop('TwistUpperAngle', 'Twist Limits', num(45)),
      prop('UpperAngle', 'Limits', num(45)),
      prop('EnableSkinning', 'Behavior', bool(false)),
    ],
  },
  {
    className: 'HingeConstraint',
    superClass: 'Constraint',
    creatable: true,
    description: 'Rotates around one axis with motor, servo, and limit modes.',
    glyph: 'HC',
    glyphColor: '#e39a48',
    properties: [
      enumProp('ActuatorType', 'Motor', ACTUATORS),
      prop('AngularResponsiveness', 'Servo', num(45), { min: 0 }),
      prop('AngularSpeed', 'Servo', num(0)),
      prop('AngularVelocity', 'Motor', num(0)),
      prop('CurrentAngle', 'Derived Data', num(0), { readOnly: true }),
      prop('LimitsEnabled', 'Limits', bool(false)),
      prop('LowerAngle', 'Limits', num(-45)),
      prop('UpperAngle', 'Limits', num(45)),
      prop('MotorMaxAcceleration', 'Motor', num(500000), { min: 0 }),
      prop('MotorMaxTorque', 'Motor', num(0), { min: 0 }),
      prop('Radius', 'Appearance', num(0.15), { min: 0 }),
      prop('Restitution', 'Limits', num(0), { min: 0, max: 1 }),
      prop('ServoMaxTorque', 'Servo', num(0), { min: 0 }),
      prop('TargetAngle', 'Servo', num(0)),
    ],
  },
  {
    className: 'UniversalConstraint',
    superClass: 'Constraint',
    creatable: true,
    description: 'Allows rotation around two perpendicular axes.',
    glyph: 'UC',
    glyphColor: '#da9147',
    properties: [
      prop('LimitsEnabled', 'Limits', bool(false)),
      prop('MaxAngle', 'Limits', num(45)),
      prop('Radius', 'Appearance', num(0.15), { min: 0 }),
      prop('Restitution', 'Limits', num(0), { min: 0, max: 1 }),
    ],
  },
  {
    className: 'SlidingBallConstraint',
    superClass: 'Constraint',
    creatable: false,
    description: 'Abstract base for constraints that slide along an axis.',
    glyph: 'SC',
    glyphColor: '#8a8a8a',
    properties: [
      enumProp('ActuatorType', 'Motor', ACTUATORS),
      prop('CurrentPosition', 'Derived Data', num(0), { readOnly: true }),
      prop('LimitsEnabled', 'Limits', bool(false)),
      prop('LinearResponsiveness', 'Servo', num(45), { min: 0 }),
      prop('LowerLimit', 'Limits', num(-10)),
      prop('UpperLimit', 'Limits', num(10)),
      prop('MotorMaxAcceleration', 'Motor', num(500000), { min: 0 }),
      prop('MotorMaxForce', 'Motor', num(0), { min: 0 }),
      prop('Restitution', 'Limits', num(0), { min: 0, max: 1 }),
      prop('ServoMaxForce', 'Servo', num(0), { min: 0 }),
      prop('Size', 'Appearance', num(0.5), { min: 0 }),
      prop('Speed', 'Servo', num(0)),
      prop('TargetPosition', 'Servo', num(0)),
      prop('Velocity', 'Motor', num(0)),
    ],
  },
  {
    className: 'PrismaticConstraint',
    superClass: 'SlidingBallConstraint',
    creatable: true,
    description: 'Slides along one axis with limits, motor, or servo.',
    glyph: 'PR',
    glyphColor: '#d98e45',
    properties: [],
  },
  {
    className: 'CylindricalConstraint',
    superClass: 'SlidingBallConstraint',
    creatable: true,
    description: 'Combines sliding and rotation around one axis.',
    glyph: 'CY',
    glyphColor: '#d98e45',
    properties: [
      enumProp('AngularActuatorType', 'Angular Motor', ACTUATORS),
      prop('AngularLimitsEnabled', 'Angular Limits', bool(false)),
      prop('AngularResponsiveness', 'Angular Servo', num(45), { min: 0 }),
      prop('AngularRestitution', 'Angular Limits', num(0), { min: 0, max: 1 }),
      prop('AngularSpeed', 'Angular Servo', num(0)),
      prop('AngularVelocity', 'Angular Motor', num(0)),
      prop('CurrentAngle', 'Derived Data', num(0), { readOnly: true }),
      prop('InclinationAngle', 'Angular Limits', num(0)),
      prop('LowerAngle', 'Angular Limits', num(-45)),
      prop('UpperAngle', 'Angular Limits', num(45)),
      prop('MotorMaxAngularAcceleration', 'Angular Motor', num(500000), { min: 0 }),
      prop('MotorMaxTorque', 'Angular Motor', num(0), { min: 0 }),
      prop('RotationAxisVisible', 'Appearance', bool(false)),
      prop('ServoMaxTorque', 'Angular Servo', num(0), { min: 0 }),
      prop('TargetAngle', 'Angular Servo', num(0)),
      prop('WorldRotationAxis', 'Derived World Data', v3(1, 0, 0), { readOnly: true }),
    ],
  },
  {
    className: 'RodConstraint',
    superClass: 'Constraint',
    creatable: true,
    description: 'Keeps two Attachments at a fixed distance.',
    glyph: 'RD',
    glyphColor: '#d99149',
    properties: [
      prop('CurrentDistance', 'Derived Data', num(0), { readOnly: true }),
      prop('Length', 'Behavior', num(1), { min: 0 }),
      prop('LimitAngle0', 'Limits', num(0)),
      prop('LimitAngle1', 'Limits', num(0)),
      prop('LimitsEnabled', 'Limits', bool(false)),
      prop('Thickness', 'Appearance', num(0.1), { min: 0 }),
    ],
  },
  {
    className: 'RopeConstraint',
    superClass: 'Constraint',
    creatable: true,
    description: 'Limits two Attachments to a maximum rope length.',
    glyph: 'RP',
    glyphColor: '#d99149',
    properties: [
      prop('CurrentDistance', 'Derived Data', num(0), { readOnly: true }),
      prop('Length', 'Behavior', num(10), { min: 0 }),
      prop('Restitution', 'Behavior', num(0), { min: 0, max: 1 }),
      prop('Thickness', 'Appearance', num(0.1), { min: 0 }),
      prop('WinchEnabled', 'Winch', bool(false)),
      prop('WinchForce', 'Winch', num(0), { min: 0 }),
      prop('WinchResponsiveness', 'Winch', num(45), { min: 0 }),
      prop('WinchSpeed', 'Winch', num(0)),
      prop('WinchTarget', 'Winch', num(0), { min: 0 }),
    ],
  },
  {
    className: 'SpringConstraint',
    superClass: 'Constraint',
    creatable: true,
    description: 'Applies spring and damping forces between two Attachments.',
    glyph: 'SP',
    glyphColor: '#d99149',
    properties: [
      ...springLike(),
      prop('CurrentLength', 'Derived Data', num(0), { readOnly: true }),
      prop('FreeLength', 'Behavior', num(1), { min: 0 }),
      prop('MaxForce', 'Behavior', num(0), { min: 0 }),
      prop('MaxLength', 'Limits', num(10), { min: 0 }),
      prop('MinLength', 'Limits', num(0), { min: 0 }),
    ],
  },
  {
    className: 'TorsionSpringConstraint',
    superClass: 'Constraint',
    creatable: true,
    description: 'Applies spring torque around an axis.',
    glyph: 'TS',
    glyphColor: '#d99149',
    properties: [
      ...springLike().filter((item) => item.name !== 'Thickness'),
      prop('CurrentAngle', 'Derived Data', num(0), { readOnly: true }),
      prop('MaxAngle', 'Limits', num(45)),
      prop('MaxTorque', 'Behavior', num(0), { min: 0 }),
      prop('Restitution', 'Limits', num(0), { min: 0, max: 1 }),
    ],
  },
  {
    className: 'AnimationConstraint',
    superClass: 'Constraint',
    creatable: true,
    description: 'Animation joint constraint used by upgraded avatar rigs.',
    glyph: 'AN',
    glyphColor: '#c482dc',
    properties: [
      prop('IsKinematic', 'Behavior', bool(false)),
      prop('MaxForce', 'Behavior', num(0), { min: 0 }),
      prop('MaxTorque', 'Behavior', num(0), { min: 0 }),
      prop('LinearStrength', 'Behavior', num(0), { min: 0 }),
      prop('LinearDamping', 'Behavior', num(0), { min: 0 }),
      prop('AngularStrength', 'Behavior', num(0), { min: 0 }),
      prop('AngularDamping', 'Behavior', num(0), { min: 0 }),
      prop('EnableSkinning', 'Behavior', bool(false)),
    ],
  },
  {
    className: 'AlignPosition',
    superClass: 'Constraint',
    creatable: true,
    description: 'Moves an assembly toward a target position.',
    glyph: 'AP',
    glyphColor: '#62b6cb',
    properties: [
      prop('ApplyAtCenterOfMass', 'Behavior', bool(false)),
      prop('MaxVelocity', 'Force', num(10000), { min: 0 }),
      prop('Position', 'Goal', v3()),
      prop('ReactionForceEnabled', 'Behavior', bool(false)),
      prop('Responsiveness', 'Force', num(10), { min: 0 }),
      prop('RigidityEnabled', 'Force', bool(false)),
      enumProp('ForceLimitMode', 'Force', ['Magnitude', 'PerAxis']),
      enumProp('ForceRelativeTo', 'Force', AXES),
      prop('MaxAxesForce', 'Force', v3(10000, 10000, 10000)),
      prop('MaxForce', 'Force', num(10000), { min: 0 }),
      enumProp('Mode', 'Behavior', ['TwoAttachment', 'OneAttachment']),
    ],
  },
  {
    className: 'AlignOrientation',
    superClass: 'Constraint',
    creatable: true,
    description: 'Rotates an assembly toward a target orientation.',
    glyph: 'AO',
    glyphColor: '#62b6cb',
    properties: [
      prop('CFrame', 'Goal', cf()),
      prop('MaxAngularVelocity', 'Torque', num(10000), { min: 0 }),
      prop('PrimaryAxisOnly', 'Behavior', bool(false)),
      prop('ReactionTorqueEnabled', 'Behavior', bool(false)),
      prop('Responsiveness', 'Torque', num(10), { min: 0 }),
      prop('RigidityEnabled', 'Torque', bool(false)),
      enumProp('AlignType', 'Behavior', ['AllAxes', 'PrimaryAxisParallel', 'PrimaryAxisPerpendicular', 'PrimaryAxisLookAt']),
      prop('MaxTorque', 'Torque', num(10000), { min: 0 }),
      enumProp('Mode', 'Behavior', ['TwoAttachment', 'OneAttachment']),
      prop('PrimaryAxis', 'Goal', v3(1, 0, 0)),
      prop('SecondaryAxis', 'Goal', v3(0, 1, 0)),
      prop('LookAtPosition', 'Goal', v3()),
    ],
  },
  {
    className: 'LinearVelocity',
    superClass: 'Constraint',
    creatable: true,
    description: 'Maintains vector, line, or plane velocity.',
    glyph: 'LV',
    glyphColor: '#62b6cb',
    properties: [
      enumProp('VelocityConstraintMode', 'Behavior', ['Vector', 'Line', 'Plane']),
      prop('ReactionForceEnabled', 'Behavior', bool(false)),
      prop('VectorVelocity', 'Velocity', v3()),
      prop('LineDirection', 'Velocity', v3(1, 0, 0)),
      prop('LineVelocity', 'Velocity', num(0)),
      prop('PlaneVelocity', 'Velocity', v2()),
      prop('PrimaryTangentAxis', 'Velocity', v3(1, 0, 0)),
      prop('SecondaryTangentAxis', 'Velocity', v3(0, 1, 0)),
      prop('MaxForce', 'Force', num(1000), { min: 0 }),
      prop('MaxAxesForce', 'Force', v3(1000, 1000, 1000)),
      prop('MaxPlanarAxesForce', 'Force', v2(1000, 1000)),
      enumProp('ForceLimitMode', 'Force', ['Magnitude', 'PerAxis']),
      enumProp('RelativeTo', 'Velocity', AXES),
      prop('ForceLimitsEnabled', 'Force', bool(true)),
    ],
  },
  {
    className: 'AngularVelocity',
    superClass: 'Constraint',
    creatable: true,
    description: 'Maintains angular velocity around an axis.',
    glyph: 'AV',
    glyphColor: '#62b6cb',
    properties: [
      prop('AngularVelocity', 'Velocity', v3()),
      prop('MaxTorque', 'Torque', num(1000), { min: 0 }),
      prop('ReactionTorqueEnabled', 'Behavior', bool(false)),
      enumProp('RelativeTo', 'Velocity', AXES),
    ],
  },
  {
    className: 'VectorForce',
    superClass: 'Constraint',
    creatable: true,
    description: 'Applies a constant directional force.',
    glyph: 'VF',
    glyphColor: '#62b6cb',
    properties: [
      prop('ApplyAtCenterOfMass', 'Behavior', bool(false)),
      prop('Force', 'Force', v3(1000, 0, 0)),
      enumProp('RelativeTo', 'Force', AXES),
    ],
  },
  {
    className: 'LineForce',
    superClass: 'Constraint',
    creatable: true,
    description: 'Applies force along the line between two Attachments.',
    glyph: 'LF',
    glyphColor: '#62b6cb',
    properties: [
      prop('ApplyAtCenterOfMass', 'Behavior', bool(false)),
      prop('InverseSquareLaw', 'Force', bool(false)),
      prop('Magnitude', 'Force', num(1000)),
      prop('MaxForce', 'Force', num(10000), { min: 0 }),
      prop('ReactionForceEnabled', 'Behavior', bool(false)),
    ],
  },
  {
    className: 'Torque',
    superClass: 'Constraint',
    creatable: true,
    description: 'Applies constant torque to an assembly.',
    glyph: 'TQ',
    glyphColor: '#62b6cb',
    properties: [prop('Torque', 'Torque', v3()), enumProp('RelativeTo', 'Torque', AXES)],
  },
  {
    className: 'WeldConstraint',
    superClass: 'Instance',
    creatable: true,
    description: 'Rigidly welds two BaseParts without Attachments.',
    glyph: 'WC',
    glyphColor: '#dd9a4a',
    properties: [
      refProp('Part0', 'Data', 'BasePart'),
      refProp('Part1', 'Data', 'BasePart'),
      prop('Enabled', 'Behavior', bool(true)),
      prop('Active', 'Behavior', bool(false), { readOnly: true }),
    ],
  },
  {
    className: 'NoCollisionConstraint',
    superClass: 'Instance',
    creatable: true,
    description: 'Prevents collision between two BaseParts.',
    glyph: 'NC',
    glyphColor: '#dd9a4a',
    properties: [
      refProp('Part0', 'Data', 'BasePart'),
      refProp('Part1', 'Data', 'BasePart'),
      prop('Enabled', 'Behavior', bool(true)),
    ],
  },
  {
    className: 'UIComponent',
    superClass: 'Instance',
    creatable: false,
    description: 'Abstract base for instances that modify a GuiObject.',
    glyph: 'UI',
    glyphColor: '#8a8a8a',
    properties: [],
  },
  {
    className: 'UIConstraint',
    superClass: 'UIComponent',
    creatable: false,
    description: 'Abstract base for UI layout constraints.',
    glyph: 'UI',
    glyphColor: '#8a8a8a',
    properties: [],
  },
  {
    className: 'UIAspectRatioConstraint',
    superClass: 'UIConstraint',
    creatable: true,
    description: 'Maintains a UI object aspect ratio.',
    glyph: 'AR',
    glyphColor: '#72a8d8',
    properties: [
      prop('AspectRatio', 'Layout', num(1), { min: 0 }),
      enumProp('AspectType', 'Layout', ['FitWithinMaxSize', 'ScaleWithParentSize']),
      enumProp('DominantAxis', 'Layout', ['Width', 'Height']),
    ],
  },
  {
    className: 'UISizeConstraint',
    superClass: 'UIConstraint',
    creatable: true,
    description: 'Clamps the size of a UI object.',
    glyph: 'US',
    glyphColor: '#72a8d8',
    properties: [prop('MaxSize', 'Layout', v2(10000, 10000)), prop('MinSize', 'Layout', v2())],
  },
  {
    className: 'UITextSizeConstraint',
    superClass: 'UIConstraint',
    creatable: true,
    description: 'Clamps automatically scaled UI text size.',
    glyph: 'UT',
    glyphColor: '#72a8d8',
    properties: [
      prop('MaxTextSize', 'Layout', num(100), { min: 1 }),
      prop('MinTextSize', 'Layout', num(1), { min: 1 }),
    ],
  },
  {
    className: 'PartOperation',
    superClass: 'TriangleMeshPart',
    creatable: false,
    description: 'Abstract base for solid-modeled CSG parts.',
    glyph: 'CS',
    glyphColor: '#8a8a8a',
    properties: [
      prop('SmoothingAngle', 'Appearance', num(0), { min: 0, max: 180 }),
      prop('TriangleCount', 'Part', num(0), { readOnly: true }),
      prop('UsePartColor', 'Appearance', bool(false)),
      enumProp('RenderFidelity', 'Appearance', ['Automatic', 'Precise']),
    ],
  },
  {
    className: 'UnionOperation',
    superClass: 'PartOperation',
    creatable: true,
    description: 'CSG result containing the union of solid parts.',
    glyph: 'U',
    glyphColor: '#ae7bd1',
    properties: [],
  },
  {
    className: 'NegateOperation',
    superClass: 'PartOperation',
    creatable: true,
    description: 'Subtractive volume used by Studio CSG tools.',
    glyph: 'N',
    glyphColor: '#e06b9d',
    properties: [],
  },
  {
    className: 'IntersectOperation',
    superClass: 'PartOperation',
    creatable: true,
    description: 'CSG result containing only overlapping volume.',
    glyph: 'I',
    glyphColor: '#699fd2',
    properties: [],
  },
]
